// Code generated by github.com/abhimanyu003/sttr/cmd/generate.go. DO NOT EDIT

package cmd

import (
	"fmt"
	"io"
	"os"

	"github.com/abhimanyu003/sttr/processors"
	"github.com/abhimanyu003/sttr/utils"
	"github.com/spf13/cobra"
)

var base62Encode_flag_p string

func init() {
	base62EncodeCmd.Flags().StringVarP(&base62Encode_flag_p, "prefix", "p", "", "Add prefix to encoded string")
	rootCmd.AddCommand(base62EncodeCmd)
}

var base62EncodeCmd = &cobra.Command{
	Use:     "base62-encode [string]",
	Short:   "Encode your text to Base62",
	Aliases: []string{"b62-enc", "b62-encode"},
	Args:    cobra.MaximumNArgs(1),
	RunE: func(cmd *cobra.Command, args []string) error {
		var err error
		var out string

		flags := make([]processors.Flag, 0)
		p := processors.Base62Encode{}
		flags = append(flags, processors.Flag{Short: "p", Value: base62Encode_flag_p})

		if len(args) == 0 {
			// Handle stdin/interactive input
			in := []byte(utils.ReadMultilineInput())
			out, err = p.Transform(in, flags...)
			if err != nil {
				return err
			}
		} else {
			// Check if it's a file
			if fi, err := os.Stat(args[0]); err == nil && !fi.IsDir() {
				// It's a file - check if we should use streaming
				const largeFileThreshold = 10 * 1024 * 1024 // 10MB
				
				// Check if processor supports streaming
				if streamingProc, ok := interface{}(p).(interface {
					CanStream() bool
					PreferStream() bool
					TransformStream(io.Reader, io.Writer, ...processors.Flag) error
				}); ok && streamingProc.CanStream() && (fi.Size() > largeFileThreshold || streamingProc.PreferStream()) {
					
					// Use streaming
					file, err := os.Open(args[0])
					if err != nil {
						return err
					}
					defer file.Close()
					
					err = streamingProc.TransformStream(file, os.Stdout, flags...)
					return err
				} else {
					// Use traditional method
					d, err := os.ReadFile(args[0])
					if err != nil {
						return err
					}
					out, err = p.Transform(d, flags...)
					if err != nil {
						return err
					}
				}
			} else {
				// Not a file, treat as string input
				out, err = p.Transform([]byte(args[0]), flags...)
				if err != nil {
					return err
				}
			}
		}

		_, err = fmt.Fprint(os.Stdout, out)
		return err
	},
}
