// Code generated by github.com/abhimanyu003/sttr/cmd/generate.go. DO NOT EDIT

package cmd

import (
	"fmt"
	"os"

	"github.com/abhimanyu003/sttr/processors"
	"github.com/abhimanyu003/sttr/utils"
	"github.com/spf13/cobra"
)

var blake2B_flag_s uint

func init() {	
	blake2BCmd.Flags().UintVarP(&blake2B_flag_s, "size", "s", 64, "Hash size in bytes (1-64)")
	rootCmd.AddCommand(blake2BCmd)
}

var blake2BCmd = &cobra.Command{
	Use:     "blake2b [string]",
	Short:   "Get the BLAKE2b hash of your text",
	Aliases: []string{"blake2b-hash", "blake2b-sum"},
	Args:    cobra.MaximumNArgs(1),
	RunE: func(cmd *cobra.Command, args []string) error {
		var err error
		var in []byte
		var out string

		if len(args) == 0 {
			in = []byte(utils.ReadMultilineInput())
		} else {
			if fi, err := os.Stat(args[0]); err == nil && !fi.IsDir() {
				d, err := os.ReadFile(args[0])
				if err != nil {
					return err
				}
				in = d
			} else {
				in = []byte(args[0])
			}
		}

		flags := make([]processors.Flag, 0)
		p := processors.BLAKE2b{}
		flags = append(flags, processors.Flag{Short: "s", Value: blake2B_flag_s})

		out, err = p.Transform(in, flags...)
		if err != nil {
			return err
		}

		_, err = fmt.Fprint(os.Stdout, out)
		return err
	},
}
