// Code generated by github.com/abhimanyu003/sttr/cmd/generate.go. DO NOT EDIT

package cmd

import (
	"fmt"
	"os"

	"github.com/abhimanyu003/sttr/processors"
	"github.com/abhimanyu003/sttr/utils"
	"github.com/spf13/cobra"
)

var (		
	qr_flag_s uint		
	qr_flag_l string		
	qr_flag_f bool
)

func init() {	
	qrCmd.Flags().UintVarP(&qr_flag_s, "size", "s", 100, "QR code size hint (affects error correction and quiet zone)")
	qrCmd.Flags().StringVarP(&qr_flag_l, "level", "l", "H", "Error correction level (L/low, M/medium, H/high)")	
	qrCmd.Flags().BoolVarP(&qr_flag_f, "full", "f", false, "Use full blocks instead of half blocks")
	rootCmd.AddCommand(qrCmd)
}

var qrCmd = &cobra.Command{
	Use:     "qr [string]",
	Short:   "Generate QR code in terminal",
	Aliases: []string{"qrcode", "qr-code"},
	Args:    cobra.MaximumNArgs(1),
	RunE: func(cmd *cobra.Command, args []string) error {
		var err error
		var out string

		flags := make([]processors.Flag, 0)
		p := processors.QRCode{}
		flags = append(flags, processors.Flag{Short: "s", Value: qr_flag_s})
		flags = append(flags, processors.Flag{Short: "l", Value: qr_flag_l})
		flags = append(flags, processors.Flag{Short: "f", Value: qr_flag_f})

		if len(args) == 0 {
			// Handle stdin/interactive input
			in := []byte(utils.ReadMultilineInput())
			out, err = p.Transform(in, flags...)
			if err != nil {
				return err
			}
		} else {
			// Check if it's a file
			if fi, err := os.Stat(args[0]); err == nil && !fi.IsDir() {
				// It's a file - check if we should use streaming
				const largeFileThreshold = 10 * 1024 * 1024 // 10MB
				
				// Use central streaming function for all processors
				if processors.CanStream(p) && (fi.Size() > largeFileThreshold || processors.PreferStream(p)) {
					// Use streaming
					file, err := os.Open(args[0])
					if err != nil {
						return err
					}
					defer file.Close()
					
					err = processors.TransformStream(p, file, os.Stdout, flags...)
					return err
				} else {
					// Use traditional method for small files
					d, err := os.ReadFile(args[0])
					if err != nil {
						return err
					}
					out, err = p.Transform(d, flags...)
					if err != nil {
						return err
					}
				}
			} else {
				// Not a file, treat as string input
				out, err = p.Transform([]byte(args[0]), flags...)
				if err != nil {
					return err
				}
			}
		}

		_, err = fmt.Fprint(os.Stdout, out)
		return err
	},
}
