// Code generated by github.com/abhimanyu003/sttr/cmd/generate.go. DO NOT EDIT

package cmd

import (
	"fmt"
	"os"

	"github.com/abhimanyu003/sttr/processors"
	"github.com/abhimanyu003/sttr/utils"
	"github.com/spf13/cobra"
)

var base58Encode_flag_c bool

func init() {	
	base58EncodeCmd.Flags().BoolVarP(&base58Encode_flag_c, "check", "c", false, "Use Base58Check encoding (with checksum)")
	rootCmd.AddCommand(base58EncodeCmd)
}

var base58EncodeCmd = &cobra.Command{
	Use:     "base58-encode [string]",
	Short:   "Encode your text to Base58",
	Aliases: []string{"b58-enc", "b58-encode"},
	Args:    cobra.MaximumNArgs(1),
	RunE: func(cmd *cobra.Command, args []string) error {
		var err error
		var in []byte
		var out string

		if len(args) == 0 {
			in = []byte(utils.ReadMultilineInput())
		} else {
			if fi, err := os.Stat(args[0]); err == nil && !fi.IsDir() {
				d, err := os.ReadFile(args[0])
				if err != nil {
					return err
				}
				in = d
			} else {
				in = []byte(args[0])
			}
		}

		flags := make([]processors.Flag, 0)
		p := processors.Base58Encode{}
		flags = append(flags, processors.Flag{Short: "c", Value: base58Encode_flag_c})

		out, err = p.Transform(in, flags...)
		if err != nil {
			return err
		}

		_, err = fmt.Fprint(os.Stdout, out)
		return err
	},
}
