// Code generated by github.com/abhimanyu003/sttr/cmd/generate.go. DO NOT EDIT

package cmd

import (
	"fmt"
	"os"

	"github.com/abhimanyu003/sttr/processors"
	"github.com/abhimanyu003/sttr/utils"
	"github.com/spf13/cobra"
)

var base62Encode_flag_p string

func init() {
	base62EncodeCmd.Flags().StringVarP(&base62Encode_flag_p, "prefix", "p", "", "Add prefix to encoded string")
	rootCmd.AddCommand(base62EncodeCmd)
}

var base62EncodeCmd = &cobra.Command{
	Use:     "base62-encode [string]",
	Short:   "Encode your text to Base62",
	Aliases: []string{"b62-enc", "b62-encode"},
	Args:    cobra.MaximumNArgs(1),
	RunE: func(cmd *cobra.Command, args []string) error {
		var err error
		var in []byte
		var out string

		if len(args) == 0 {
			in = []byte(utils.ReadMultilineInput())
		} else {
			if fi, err := os.Stat(args[0]); err == nil && !fi.IsDir() {
				d, err := os.ReadFile(args[0])
				if err != nil {
					return err
				}
				in = d
			} else {
				in = []byte(args[0])
			}
		}

		flags := make([]processors.Flag, 0)
		p := processors.Base62Encode{}
		flags = append(flags, processors.Flag{Short: "p", Value: base62Encode_flag_p})

		out, err = p.Transform(in, flags...)
		if err != nil {
			return err
		}

		_, err = fmt.Fprint(os.Stdout, out)
		return err
	},
}
