// Code generated by github.com/abhimanyu003/sttr/cmd/generate.go. DO NOT EDIT

package cmd

import (
	"fmt"
	"os"

	"github.com/abhimanyu003/sttr/processors"
	"github.com/abhimanyu003/sttr/utils"
	"github.com/spf13/cobra"
)

var crockfordBase32Decode_flag_v bool

func init() {	
	crockfordBase32DecodeCmd.Flags().BoolVarP(&crockfordBase32Decode_flag_v, "verify", "v", false, "Verify Crockford checksum")
	rootCmd.AddCommand(crockfordBase32DecodeCmd)
}

var crockfordBase32DecodeCmd = &cobra.Command{
	Use:     "crockford-base32-decode [string]",
	Short:   "Decode your Crockford Base32 text",
	Aliases: []string{"crockford-b32-dec", "cb32-decode"},
	Args:    cobra.MaximumNArgs(1),
	RunE: func(cmd *cobra.Command, args []string) error {
		var err error
		var in []byte
		var out string

		if len(args) == 0 {
			in = []byte(utils.ReadMultilineInput())
		} else {
			if fi, err := os.Stat(args[0]); err == nil && !fi.IsDir() {
				d, err := os.ReadFile(args[0])
				if err != nil {
					return err
				}
				in = d
			} else {
				in = []byte(args[0])
			}
		}

		flags := make([]processors.Flag, 0)
		p := processors.CrockfordBase32Decode{}
		flags = append(flags, processors.Flag{Short: "v", Value: crockfordBase32Decode_flag_v})

		out, err = p.Transform(in, flags...)
		if err != nil {
			return err
		}

		_, err = fmt.Fprint(os.Stdout, out)
		return err
	},
}
