// Code generated by github.com/abhimanyu003/sttr/cmd/generate.go. DO NOT EDIT

package cmd

import (
	"fmt"
	"os"

	"github.com/abhimanyu003/sttr/processors"
	"github.com/abhimanyu003/sttr/utils"
	"github.com/spf13/cobra"
)

var crc32_flag_p string

func init() {
	crc32Cmd.Flags().StringVarP(&crc32_flag_p, "polynomial", "p", "ieee", "CRC32 polynomial (ieee, castagnoli, koopman)")
	rootCmd.AddCommand(crc32Cmd)
}

var crc32Cmd = &cobra.Command{
	Use:     "crc32 [string]",
	Short:   "Get the CRC32 checksum of your text",
	Aliases: []string{"crc32-sum", "crc32-checksum"},
	Args:    cobra.MaximumNArgs(1),
	RunE: func(cmd *cobra.Command, args []string) error {
		var err error
		var in []byte
		var out string

		if len(args) == 0 {
			in = []byte(utils.ReadMultilineInput())
		} else {
			if fi, err := os.Stat(args[0]); err == nil && !fi.IsDir() {
				d, err := os.ReadFile(args[0])
				if err != nil {
					return err
				}
				in = d
			} else {
				in = []byte(args[0])
			}
		}

		flags := make([]processors.Flag, 0)
		p := processors.CRC32{}
		flags = append(flags, processors.Flag{Short: "p", Value: crc32_flag_p})

		out, err = p.Transform(in, flags...)
		if err != nil {
			return err
		}

		_, err = fmt.Fprint(os.Stdout, out)
		return err
	},
}
